package com.mrs.enpoint.feature.auditlog.enums;

public enum AuditAction {
	
	USER_REGISTRATION,
    USER_BLOCK,
    USER_INACTIVE,
    USER_UNBLOCK,
    PASSWORD_RESET,
    PASSWORD_CHANGE,

    CREATE_PLAN,
    UPDATE_PLAN_NAME,
    DELETE_PLAN,
    UPDATE_PRICE,
    ACTIVATE_PLAN,
    DEACTIVATE_PLAN,

    CREATE_OFFER,
    UPDATE_OFFER,
    ACTIVATE_OFFER,
    DEACTIVATE_OFFER,

    MAP_PLAN_OFFER,
    UNMAP_PLAN_OFFER,

    CREATE_CATEGORY,
    UPDATE_CATEGORY,
    ACTIVATE_CATEGORY,
    DEACTIVATE_CATEGORY,

    CREATE_OPERATOR,
    UPDATE_OPERATOR,
    ACTIVATE_OPERATOR,
    DEACTIVATE_OPERATOR,

    RECHARGE_SUCCESS,
    RECHARGE_FAILED,
    REFUND_COMPLETED,
    PAYMENT_RETRY,
    
    SAVE_NUMBER,         
    UPDATE_SAVED_NUMBER, 
    DELETE_SAVED_NUMBER,
    
    CONFIG_UPDATE,
    CRON_JOB_EXECUTION
    
}
